######################################################################
# Automatically generated by qmake (2.01a) ??? ??? 21 22:51:30 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += main_window.h
SOURCES += main.cpp main_window.cpp
RESOURCES += gui.qrc
