######################################################################
# Automatically generated by qmake (2.01a) ??? ??? 19 00:50:59 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
